data:
    dataset: "LSUN"
    category: "bedroom"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8

model:
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    steps: 20

train:
    lr: 0.0001
    epoch: 5
    batch_size: 64
    model_type: 'Resnet50'
    dataset: "./dataset/dnf/train/lsun"
    val: "./dataset/dnf/val/lsun"
    ckpt_dir: "./weights"

test:
    model_type: 'Resnet50'
    root: "./dataset/test"
    model: ""

i2n:
    diffusion: "./weights/diffsuion/model-2388000.ckpt"
    root: "./dataset/source/train/lsun"
    target: "./dataset/dnf/train/lsun"


exp:
    name: "demo_program"
